const $=s=>document.querySelector(s);const modal=$('#authModal');let mode='login';
function toast(t){const x=$('#toast');x.textContent=t;x.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display='none',2600)}
function openAuth(next='login'){mode=next;updateAuth();modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function closeAuth(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
function updateAuth(){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));$('#authTitle').textContent=mode==='login'?'تسجيل الدخول':'إنشاء حساب';$('#nameInput').hidden=mode==='login';$('#authSubmit').textContent=mode==='login'?'دخول إلى المنصة':'إنشاء الحساب';$('#authNote').textContent=''}
function refreshUser(){const user=JSON.parse(localStorage.getItem('codespaceUser')||'null');const logged=!!user;$('#loginBtn').hidden=logged;$('#logoutBtn').hidden=!logged;$('#welcome').textContent=logged?`أهلاً ${user.name} 👋`:'أهلاً بك في CodeSpace 👋';if(logged){$('#progressValue').textContent=localStorage.getItem('codespaceProgress')||'0%';$('#completedValue').textContent=localStorage.getItem('codespaceCompleted')||'0'}}
$('#loginBtn').onclick=()=>openAuth('login');$('#signupBtn').onclick=()=>openAuth('signup');$('#closeModal').onclick=closeAuth;modal.onclick=e=>{if(e.target===modal)closeAuth()};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{mode=t.dataset.mode;updateAuth()});
$('#authSubmit').onclick=()=>{const email=$('#emailInput').value.trim();const password=$('#passwordInput').value;const name=$('#nameInput').value.trim();if(!email||!password||(mode==='signup'&&!name)){toast('من فضلك أكمل البيانات');return}if(mode==='signup'){localStorage.setItem('codespaceUser',JSON.stringify({name,email}));toast('تم إنشاء الحساب على جهازك بنجاح')}else{const user=JSON.parse(localStorage.getItem('codespaceUser')||'null');if(user&&user.email!==email){toast('هذا الحساب التجريبي مرتبط بالبريد المستخدم عند الإنشاء');return}localStorage.setItem('codespaceUser',JSON.stringify({name:user?.name||email.split('@')[0],email}));toast('تم تسجيل الدخول')}closeAuth();refreshUser()};
$('#logoutBtn').onclick=()=>{localStorage.removeItem('codespaceUser');refreshUser();toast('تم تسجيل الخروج')};
document.querySelectorAll('.courseBtn').forEach(btn=>btn.onclick=()=>{const user=localStorage.getItem('codespaceUser');if(!user){openAuth('login');toast('سجّل الدخول أولاً لبدء المسار');return}toast('تم فتح مسار '+btn.dataset.course);location.hash='dashboard'});
$('#lessonBtn').onclick=()=>{const user=localStorage.getItem('codespaceUser');if(!user){openAuth('login');toast('سجّل الدخول أولاً لبدء المحاضرة');return}localStorage.setItem('codespaceCompleted','1');localStorage.setItem('codespaceProgress','25%');refreshUser();toast('تم فتح المحاضرة الأولى وتسجيلها كمكتملة');location.hash='dashboard'};
refreshUser();
